"""initial schema

Revision ID: 3afe401d7324
Revises: 
Create Date: 2026-05-11 16:40:54.268831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3afe401d7324'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('address', sa.String(length=160), nullable=True),
    sa.Column('has_pavilion', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lat', 'lon', name='uq_bus_stop_coords')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_number', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('total_length', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_length > 0', name='ck_route_total_length_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'MANAGER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('vehicle_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('analytics_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bus_stop_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_stop', sa.Integer(), nullable=False),
    sa.Column('to_stop', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('avg_time', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.CheckConstraint('distance > 0', name='ck_bsc_distance_positive'),
    sa.ForeignKeyConstraint(['from_stop'], ['bus_stops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_stop'], ['bus_stops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bus_stop_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.CheckConstraint('order_num > 0', name='ck_bsr_order_positive'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stop_id'], ['bus_stops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'order_num', name='uq_bsr_route_order')
    )
    op.create_table('passenger_flows',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('passengers >= 0', name='ck_pf_passengers_non_negative'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stop_id'], ['bus_stops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passenger_flows_measured_at'), 'passenger_flows', ['measured_at'], unique=False)
    op.create_index(op.f('ix_passenger_flows_route_id'), 'passenger_flows', ['route_id'], unique=False)
    op.create_table('vehicle_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.CheckConstraint('capacity > 0', name='ck_vehicle_model_capacity_positive'),
    sa.ForeignKeyConstraint(['type_id'], ['vehicle_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=15), nullable=False),
    sa.Column('year_of_make', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('year_of_make BETWEEN 1990 AND 2100', name='ck_vehicle_year_range'),
    sa.ForeignKeyConstraint(['model_id'], ['vehicle_models.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate')
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('start_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_ts', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    op.drop_table('vehicles')
    op.drop_table('vehicle_models')
    op.drop_index(op.f('ix_passenger_flows_route_id'), table_name='passenger_flows')
    op.drop_index(op.f('ix_passenger_flows_measured_at'), table_name='passenger_flows')
    op.drop_table('passenger_flows')
    op.drop_table('bus_stop_routes')
    op.drop_table('bus_stop_connections')
    op.drop_table('analytics_reports')
    op.drop_table('vehicle_types')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_table('users')
    op.drop_table('routes')
    op.drop_table('bus_stops')
    # ### end Alembic commands ###
